module.exports = {
  id: "grok",
  name: "Grok (xAI)",
  adapter: "openai-compatible",
  defaultBaseUrl: "https://api.x.ai/v1",
  apiKeyEnv: ["XAI_API_KEY", "GROK_API_KEY"],
  baseUrlEnv: ["XAI_BASE_URL", "GROK_BASE_URL"],
  openaiCompatible: {
    bodyExtensions: {},
  },
  settingsSchema: [
    {
      key: "temperature",
      label: "Temperature",
      type: "range",
      min: 0,
      max: 2,
      step: 0.1,
      decimals: 1,
      capability: "temperature",
    },
    {
      key: "topP",
      label: "Top P",
      type: "range",
      min: 0,
      max: 1,
      step: 0.05,
      decimals: 2,
      capability: "topP",
    },
    {
      key: "maxOutputTokens",
      label: "Max Output Tokens",
      type: "number",
      min: 128,
      max: 8192,
      step: 64,
      capability: "maxTokens",
    },
    {
      key: "stream",
      label: "Streaming",
      type: "toggle",
      capability: "stream",
    },
  ],
  models: [
    { id: "grok-4", name: "grok-4" },
    { id: "grok-4-fast-non-reasoning", name: "grok-4-fast-non-reasoning" },
  ],
  parameterPolicy: {
    blockedBodyParams: ["presence_penalty", "frequency_penalty"],
  },
  capabilities: {
    stream: true,
    temperature: true,
    topP: true,
    maxTokens: true,
    presencePenalty: false,
    frequencyPenalty: false,
    webSearch: false,
    tools: false,
    thinking: false,
  },
};
