const VALIDATION_ISSUE_CODES = Object.freeze({
  OBJECT_REQUIRED: "OBJECT_REQUIRED",
  SECTION_RESULTS_NOT_OBJECT: "SECTION_RESULTS_NOT_OBJECT",
  CHANGES_EMPTY: "CHANGES_EMPTY",
  SOURCE_MISSING: "SOURCE_MISSING",
  WRITABLE_REF_INVALID: "WRITABLE_REF_INVALID",
  SUPPORT_REF_INVALID: "SUPPORT_REF_INVALID",
  EVIDENCE_MESSAGE_INVALID: "EVIDENCE_MESSAGE_INVALID",
  TEXT_LENGTH_EXCEEDED: "TEXT_LENGTH_EXCEEDED",
  TOOL_ARGUMENTS_INVALID_JSON: "TOOL_ARGUMENTS_INVALID_JSON",
  STRUCTURED_OUTPUT_INCOMPLETE: "STRUCTURED_OUTPUT_INCOMPLETE",
  STRUCTURED_OUTPUT_MISSING: "STRUCTURED_OUTPUT_MISSING",
  CONTRACT_INVALID: "CONTRACT_INVALID",
});

module.exports = { VALIDATION_ISSUE_CODES };
