const safetyThresholdOptions = [
  { value: "HARM_BLOCK_THRESHOLD_UNSPECIFIED", label: "Default" },
  { value: "OFF", label: "Off (disable filter)" },
  { value: "BLOCK_NONE", label: "Block none" },
  { value: "BLOCK_ONLY_HIGH", label: "Block only high" },
  { value: "BLOCK_MEDIUM_AND_ABOVE", label: "Block medium and above" },
  { value: "BLOCK_LOW_AND_ABOVE", label: "Block low and above" },
];

module.exports = {
  id: "gemini",
  name: "Gemini (Google)",
  adapter: "google-genai",
  defaultBaseUrl: "https://generativelanguage.googleapis.com",
  apiKeyEnv: ["GEMINI_API_KEY", "GOOGLE_API_KEY"],
  baseUrlEnv: ["GEMINI_BASE_URL"],
  parameterPolicy: {
    blockedBodyParams: [],
    isBodyParamAllowed: ({ model, paramName }) => {
      if (["presencePenalty", "frequencyPenalty"].includes(paramName)) return false;
      return true;
    },
  },
  settingsSchema: [
    {
      key: "temperature",
      label: "Temperature",
      type: "range",
      min: 0,
      max: 2,
      step: 0.1,
      decimals: 1,
      capability: "temperature",
    },
    {
      key: "topP",
      label: "Top P",
      type: "range",
      min: 0,
      max: 1,
      step: 0.05,
      decimals: 2,
      capability: "topP",
    },
    {
      key: "maxOutputTokens",
      label: "Max Output Tokens",
      type: "number",
      min: 128,
      max: 8192,
      step: 64,
      capability: "maxTokens",
    },
    {
      key: "stream",
      label: "Streaming",
      type: "toggle",
      capability: "stream",
    },
    {
      key: "safetyHarassment",
      label: "Safety: Harassment",
      type: "select",
      options: safetyThresholdOptions,
      default: "HARM_BLOCK_THRESHOLD_UNSPECIFIED",
    },
    {
      key: "safetyHateSpeech",
      label: "Safety: Hate speech",
      type: "select",
      options: safetyThresholdOptions,
      default: "HARM_BLOCK_THRESHOLD_UNSPECIFIED",
    },
    {
      key: "safetySexuallyExplicit",
      label: "Safety: Sexually explicit",
      type: "select",
      options: safetyThresholdOptions,
      default: "HARM_BLOCK_THRESHOLD_UNSPECIFIED",
    },
    {
      key: "safetyDangerousContent",
      label: "Safety: Dangerous content",
      type: "select",
      options: safetyThresholdOptions,
      default: "HARM_BLOCK_THRESHOLD_UNSPECIFIED",
    },
  ],
  models: [
    { id: "gemini-2.5-flash", name: "gemini-2.5-flash" },
    { id: "gemini-2.0-flash", name: "gemini-2.0-flash" },
    { id: "gemini-3-flash-preview", name: "gemini-3-flash-preview" },
  ],
  capabilities: {
    stream: true,
    temperature: true,
    topP: true,
    maxTokens: true,
    presencePenalty: false,
    frequencyPenalty: false,
    webSearch: false,
    tools: false,
    thinking: true,
  },
};
