const { VALIDATION_ISSUE_CODES } = require("../../contracts/validationIssueCodes");

const OUTPUT_REPAIR_POLICY_VERSION = 6;
const REJECTED_OUTPUT_MAX_BYTES = 256 * 1024;

const ISSUE_CODES = VALIDATION_ISSUE_CODES;

const SAFE_NORMALIZATIONS = Object.freeze({
  EMPTY_CHANGES_TO_NOOP: "EMPTY_CHANGES_TO_NOOP",
  REMOVE_EMPTY_SOURCE_ARRAYS: "REMOVE_EMPTY_SOURCE_ARRAYS",
});

module.exports = {
  OUTPUT_REPAIR_POLICY_VERSION,
  REJECTED_OUTPUT_MAX_BYTES,
  ISSUE_CODES,
  SAFE_NORMALIZATIONS,
};
